jhipster-prod-mysql:
  container_name: sampleNoCache-prod-mysql
  image : mysql
  # volumes:
  # - ~/volumes/jhipster/sampleNoCache/prod-mysql/:/var/lib/mysql/
  environment:
  - MYSQL_USER=root
  - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  - MYSQL_DATABASE=samplenocache
  ports:
  - "3306:3306"
  command: mysqld --lower_case_table_name=1

