version: '2'
services:
    jhipsternocachesampleapplication-app:
        image: jhipsternocachesampleapplication
        external_links:
            - jhipsternocachesampleapplication-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipsternocachesampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    jhipsternocachesampleapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsternocachesampleapplication-mysql
